name: ""
description: ""

## un comment baseurl variable before committing to hhs.github.io/meshrdf each time!
baseurl: /meshrdf

markdown: kramdown
permalink: /:title.html
category-list:
- Data Model
- Cheat Sheets
- Policy


kramdown:
 smart_quotes:  lsquo,rsquo,ldquo,rdquo
 input: GFM
 hard_wrap: false

##allowable list of query types are here.  Liquid filters are used to create css selectors out of this list

#query-types:
#- Getting Started
#- Aggregation
#- Descriptors and Qualifiers
#- Descriptors and Concepts
#- Predicate
#- String
#- Transitive

