name: ""
description: ""

## un comment baseurl variable before committing to hhs.github.io/mesh-rdf each time!
#baseurl: /mesh-rdf

markdown: kramdown
permalink: /:title.html
category-list:
- Data Model
- REST Interface
- Sample Queries

kramdown:
 smart_quotes:  lsquo,rsquo,ldquo,rdquo
 input: GFM

