name: ""
description: ""

url: "http://hhs.github.io/mesh-rdf"

markdown: kramdown
permalink: /:title.html
category-list:
- Data Model
- REST Interface
- Sample Queries

kramdown:
 smart_quotes:  lsquo,rsquo,ldquo,rdquo
 input: GFM

