swagger: "2.0"
info:
  description: "Lookup service for MeSH RDF"
  version: "1.0.0"
  title: "MeSH RDF API"
host: "localhost:8080"
basePath: "/mesh"
schemes:
- "https"
paths:
  /lookup/descriptor:
    get:
      summary: "Search for Descriptors, also known as Headings."
      operationId: "lookupDescriptors"
      tags:
        - "lookup"
      produces:
        - "application/json"
      parameters:
        - in: "query"
          name: "label"
          description: "Provides the text to search for in the label of each Descriptor."
          required: true
          type: "string"
          minLength: 1
        - in: "query"
          name: "match"
          description: "Determines how the label parameter is matched against Descriptor labels."
          type: "string"
          default: "exact"
          enum: ["exact", "contains", "startswith"]
        - in: "query"
          name: "limit"
          description: "Specifies the maximum number of matches to return."
          type: "integer"
          default: 10
          minimum: 1
          maximum: 50
      responses:
        200:
          description: "array of zero or more descriptors and their labels"
          examples:
            application/json:
              - resource: "http://id.nlm.nih.gov/mesh/D000071198"
                label: "Pyrin"
              - resource: "http://id.nlm.nih.gov/mesh/D000071198"
                label: "Pyrin Domain"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ResourceAndLabel"
        400:
          description: "invalid parameters"
          examples:
            application/json:
              error:
                label: [ "must not be empty" ]
          schema:
            $ref: "#/definitions/Errors"
    post:
      summary: "Search for Descriptors, alsko known as Headings"
      operationId: "lookupDescriptorsPost"
      tags:
        - "lookup"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "params"
          schema:
            type: object
            required:
              - label
            properties:
              label: 
                description: "Provides the text to search for in the label of each Descriptor."
                type: "string"
                minLength: 1
              match: 
                description: "Determines how the label parameter is matched against Descriptor labels."
                type: "string"
                default: "exact"
                enum: ["exact", "contains", "startswith"]
              limit:
                description: "Specifies the maximum number of matches to return."
                type: "integer"
                default: 10
                minimum: 1
                maximum: 50
      responses:
        200:
          description: "array of zero or more descriptors and their labels"
          examples:
            application/json:
              - resource: "http://id.nlm.nih.gov/mesh/D000071198"
                label: "Pyrin"
              - resource: "http://id.nlm.nih.gov/mesh/D000071198"
                label: "Pyrin Domain"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ResourceAndLabel"
        400:
          description: "invalid parameters"
          examples:
            application/json:
              error:
                label: [ "must not be empty" ]
          schema:
            $ref: "#/definitions/Errors"
  /lookup/pair:
    get:
      summary: "Search for Descriptor-Qualifier pairs, also known as Subheadings."
      operationId: "lookupPairs"
      tags:
        - "lookup"
      produces:
        - "application/json"
      parameters:
        - in: "query"
          name: "label"
          description: "Provides the text to search for in the label of each Quallifier."
          required: true
          type: "string"
          minLength: 1
        - in: "query"
          name: "descriptor"
          description: "Specifies the full URI or identifier of a Descriptor."
          required: true
          type: "string"
          minLength: 1
        - in: "query"
          name: "match"
          description: "Determines how the label parameter is matched against Qualifier labels."
          type: "string"
          default: "exact"
          enum: ["exact", "contains", "startswith"]
        - in: "query"
          name: "limit"
          description: "Specifies the maximum number of matches to return."
          type: "integer"
          default: 10
          minimum: 1
          maximum: 50
      responses:
        200:
          description: "array of zero or more descriptor-qualifier pairs and their labels"
          examples:
            application/json:
              - resource: "http://id.nlm.nih.gov/mesh/D000071198Q000138"
                label: "Pyrin/chemical synthesis"
              - resource: "http://id.nlm.nih.gov/mesh/D000071198Q000737"
                label: "Pyrin/chemistry"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ResourceAndLabel"
        400:
          description: "invalid parameters"
          examples:
            application/json:
              error:
                descriptor: [ "must not be empty" ]
                label: [ "must not be empty" ]
          schema:
            $ref: "#/definitions/Errors"
    post:
      summary: "Search for Descriptor-Qualifier pairs, also known as Subheadings."
      operationId: "lookupPairsPost"
      tags:
        - "lookup"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "params"
          schema:
            type: object
            required:
              - descriptor
              - label
            properties:
              label:
                description: "Provides the text to search for in the label of each Quallifier."
                type: "string"
                minLength: 1
              descriptor:
                description: "Specifies the full URI or identifier of a Descriptor."
                type: "string"
                minLength: 1
              match:
                description: "Determines how the label parameter is matched against Qualifier labels."
                type: "string"
                default: "exact"
                enum: ["exact", "contains", "startswith"]
              limit:
                description: "Specifies the maximum number of matches to return."
                type: "integer"
                default: 10
                minimum: 1
                maximum: 50
      responses:
        200:
          description: "array of zero or more descriptor-qualifier pairs and their labels"
          examples:
            application/json:
              - resource: "http://id.nlm.nih.gov/mesh/D000071198Q000138"
                label: "Pyrin/chemical synthesis"
              - resource: "http://id.nlm.nih.gov/mesh/D000071198Q000737"
                label: "Pyrin/chemistry"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ResourceAndLabel"
        400:
          description: "invalid parameters"
          examples:
            application/json:
              error:
                descriptor: [ "must not be empty" ]
                label: [ "must not be empty" ]
          schema:
            $ref: "#/definitions/Errors"
  /lookup/qualifiers:
    get:
      summary: "Return all allowed Qualifiers for a Descriptor."
      operationId: "lookupQualifiers"
      tags:
        - "lookup"
      produces:
        - "application/json"
      parameters:
        - in: "query"
          name: "descriptor"
          description: "Specifies the full URI or identifier of a Descriptor."
          required: true
          type: "string"
      responses:
        200:
          description: "array of zero or more qualifiers and their labels"
          examples:
            application/json:
              - resource: "http://id.nlm.nih.gov/mesh/Q000008"
                label: "administration & dosage"
              - resource: "http://id.nlm.nih.gov/mesh/Q000009"
                label: "adverse effects"
          schema:
            type: array
            items:
              $ref: "#/definitions/ResourceAndLabel"
        400:
          description: "invalid parameters"
          examples:
            application/json:
              error:
                descriptor: [ "must not be empty" ]
          schema:
            $ref: "#/definitions/Errors"
  /lookup/label:
    get:
      summary: "Return the label or labels for a Resource URI."
      operationId: "lookupLabels"
      tags:
        - "lookup"
      produces:
        - "application/json"
      parameters:
        - in: "query"
          name: "resource"
          description: "Specifies the full URI or identifier of a resource."
          required: true
          type: "string"
      responses:
        200:
          description: "zero or more labels"
          examples:
            application/json: 
              - Pyrin
          schema:
            type: array
            items:
              type: "string"
        400:
          description: "invalid parameters"
          examples:
            error:
              resource: [ "must not be empty" ]
          schema:
            $ref: "#/definitions/Errors"
definitions:
  Errors:
    type: "object"
    properties:
      error:
        type: "object"
  ResourceAndLabel:
    type: "object"
    properties:
      resource:
        type: "string"
        format: "uri"
      label:
        type: "string"
